Oii NPC, gimana nih gamenya kok makin gajelas sih?!?!?!#speaker : Ethan #layout : left
bip...bip....bip....#speaker : Robot(NPC) #layout : right
trrrt....trrrt....trrrrrrrrtt...
HADEEEH JANGAN RUSAK SEKARANG DONG.....#speaker : Ethan #layout : left
JAWAB DULU GUE.....
Coba restart lgi stagenya. Masa iya terjebak didalam game bentukannya begini.. DDuhh..#scene : Bug 2